# Generated by Django 4.1.2 on 2022-10-21 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='priority',
            field=models.IntegerField(choices=[(4, 4), (1, 1), (6, 6), (3, 3), (7, 7), (8, 8), (5, 5), (9, 9), (2, 2)], max_length=2),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('c', 'completed')], max_length=500),
        ),
    ]
