# Generated by Django 4.1.2 on 2022-10-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_todo_priority_alter_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('c', 'completed'), ('p', 'pending')], max_length=500),
        ),
    ]
